// SPDX-License-Identifier: Apache-2.0

//go:build integration

package roundtrip

// testAppKnownFailures is the allowlist for ako/TestApp (testdata/testapp), kept
// apart from PedApp's so each fixture's list can only shrink on its own. The
// rules are those of knownFailures in allowlist_test.go.
//
// Measured on 2026-09-27 at TestApp 11a8fca, when TestApp joined the harness
// (#743): 142 of 775 documents keep both laws. Everything listed is the #721
// classes on a larger fixture and has not been triaged per document. The #743
// entries (workflows, OData clients and external entities, whose describe
// printed a plain `create`) were struck when their rewrites learned to carry
// what describe cannot print, and the false generalization flags #721 B
// dropped struck 27 entity and association entries with them.
//
// ako/mxcli#801 struck 79 more. Executing an association's describe output goes
// through the whole-domain-model rewrite, which rebuilt every entity and
// association in the module: API entities came back Hidden and every access
// rule lost the empty member-access key Studio Pro writes. Untouched elements
// now pass through as stored and a rebuilt member access writes both keys.
// #721 L2 (client action settings: confirmations, progress bars,
// DisabledDuringExecution) struck four pages whose only loss it was.
// #721 L3 (a snippet's own parameter re-bound as a page parameter, in dynamic-text
// parameters and association data sources of WorkflowCommons snippets) struck
// seven snippets whose only loss it was.
// #721 L5 (a List View's database source over an association re-typed as an
// association source, losing its sort and search) struck two snippets and a
// page whose only loss it was, with the list markers and the null
// SourceVariable key Studio Pro writes on every list view. Four more snippets
// stopped failing exec with it — their list view is typed Administration.Account
// again, so a nested snippet call finds its $Account — and now break only
// GetPut, on the snippet call's null visibility key (C3).
// ako/mxcli#950 struck three: Rules.Entity_Menu (navigation-list items described
// as the legacy `show_page 'M.P'`, and unnamed items refused by exec) and two
// WorkflowCommons microflows whose `return if … then … else …` was described
// with a `$` in front.
// ako/mxcli#980 struck Atlas_Core.Phone_Menu and Tablet_Menu: the menu document
// writer left out each item's null AlternativeText and empty Items list, which
// Studio Pro stores on every menu item. Navigation profiles joined the harness
// with it, and round-trip from the start. It also struck
// WorkflowCommons.ConflictedWorkflowDefinitionView_ActionConfirmation, whose only
// loss was the empty OutputMappings Studio Pro stores on every nanoflow call.
var testAppKnownFailures = map[string]knownFailure{
	"association ViewAssociations.persistent_order":                                   {laws: []law{lawExec}, issue: "#721", why: "association: breaks exec on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"association WorkflowCommons.ConflictedWorkflowDefinitionView_WorkflowDefinition": {laws: []law{lawExec}, issue: "#721", why: "association: breaks exec on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"association WorkflowCommons.ConflictedWorkflowView_ConflictReasonGroup":          {laws: []law{lawExec}, issue: "#721", why: "association: breaks exec on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"association WorkflowCommons.ConflictedWorkflowView_CurrentActivitiesGroup":       {laws: []law{lawExec}, issue: "#721", why: "association: breaks exec on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"association WorkflowCommons.ConflictedWorkflowView_ExecutionPathGroup":           {laws: []law{lawExec}, issue: "#721", why: "association: breaks exec on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"association WorkflowCommons.ConflictedWorkflowView_Workflow":                     {laws: []law{lawExec}, issue: "#721", why: "association: breaks exec on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"association WorkflowCommons.ConflictedWorkflowView_WorkflowDefinition":           {laws: []law{lawExec}, issue: "#721", why: "association: breaks exec on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"association WorkflowCommons.MyInitiatedWorkflowView_Initiator":                   {laws: []law{lawExec}, issue: "#721", why: "association: breaks exec on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"association WorkflowCommons.MyInitiatedWorkflowView_ParentWorkflow":              {laws: []law{lawExec}, issue: "#721", why: "association: breaks exec on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"association WorkflowCommons.MyInitiatedWorkflowView_Workflow":                    {laws: []law{lawExec}, issue: "#721", why: "association: breaks exec on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"association WorkflowCommons.WorkflowGroupView_WorkflowGroup":                     {laws: []law{lawExec}, issue: "#721", why: "association: breaks exec on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"association WorkflowCommons.WorkflowUserTaskView_Workflow":                       {laws: []law{lawExec}, issue: "#721", why: "association: breaks exec on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"association WorkflowCommons.WorkflowUserTaskView_WorkflowEndedUserTask":          {laws: []law{lawExec}, issue: "#721", why: "association: breaks exec on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"association WorkflowCommons.WorkflowUserTaskView_WorkflowSubProcess":             {laws: []law{lawExec}, issue: "#721", why: "association: breaks exec on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"association WorkflowCommons.WorkflowUserTaskView_WorkflowUserTask":               {laws: []law{lawExec}, issue: "#721", why: "association: breaks exec on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"association WorkflowCommons.WorkflowUserTaskView_WorkflowUserTaskDefinition":     {laws: []law{lawExec}, issue: "#721", why: "association: breaks exec on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"building block Atlas_Web_Content.Alert":                                          {laws: []law{lawParse}, issue: "#721", why: "building block: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"building block Atlas_Web_Content.AlertIcon":                                      {laws: []law{lawParse}, issue: "#721", why: "building block: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"building block Atlas_Web_Content.AlertIcon_WithAction":                           {laws: []law{lawParse}, issue: "#721", why: "building block: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"building block Atlas_Web_Content.Alert_WithAction":                               {laws: []law{lawParse}, issue: "#721", why: "building block: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"building block Atlas_Web_Content.Breadcrumb":                                     {laws: []law{lawParse}, issue: "#721", why: "building block: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"building block Atlas_Web_Content.Breadcrumb_Underline":                           {laws: []law{lawParse}, issue: "#721", why: "building block: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"building block Atlas_Web_Content.Card":                                           {laws: []law{lawParse}, issue: "#721", why: "building block: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"building block Atlas_Web_Content.Card_Action":                                    {laws: []law{lawParse}, issue: "#721", why: "building block: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"building block Atlas_Web_Content.Card_ActionWithImage":                           {laws: []law{lawParse}, issue: "#721", why: "building block: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"building block Atlas_Web_Content.Card_Background":                                {laws: []law{lawParse}, issue: "#721", why: "building block: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"building block Atlas_Web_Content.Card_WithImage":                                 {laws: []law{lawParse}, issue: "#721", why: "building block: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"building block Atlas_Web_Content.Form_Horizontal":                                {laws: []law{lawParse}, issue: "#721", why: "building block: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"building block Atlas_Web_Content.Form_Horizontal_WithAction":                     {laws: []law{lawParse}, issue: "#721", why: "building block: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"building block Atlas_Web_Content.Form_Horizontal_WithTitle":                      {laws: []law{lawParse}, issue: "#721", why: "building block: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"building block Atlas_Web_Content.Form_Vertical":                                  {laws: []law{lawParse}, issue: "#721", why: "building block: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"building block Atlas_Web_Content.Form_Vertical_WithAction":                       {laws: []law{lawParse}, issue: "#721", why: "building block: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"building block Atlas_Web_Content.Form_Vertical_WithTitle":                        {laws: []law{lawParse}, issue: "#721", why: "building block: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"building block Atlas_Web_Content.Heroheader":                                     {laws: []law{lawParse}, issue: "#721", why: "building block: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"building block Atlas_Web_Content.Heroheader_Background":                          {laws: []law{lawParse}, issue: "#721", why: "building block: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"building block Atlas_Web_Content.Heroheader_WithAction":                          {laws: []law{lawParse}, issue: "#721", why: "building block: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"building block Atlas_Web_Content.ListItem_DoubleLine":                            {laws: []law{lawParse}, issue: "#721", why: "building block: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"building block Atlas_Web_Content.ListItem_SingleLine":                            {laws: []law{lawParse}, issue: "#721", why: "building block: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"building block Atlas_Web_Content.ListItem_WithImage":                             {laws: []law{lawParse}, issue: "#721", why: "building block: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"building block Atlas_Web_Content.List_Cards":                                     {laws: []law{lawParse}, issue: "#721", why: "building block: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"building block Atlas_Web_Content.List_WithImage":                                 {laws: []law{lawParse}, issue: "#721", why: "building block: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"building block Atlas_Web_Content.Master_Detail":                                  {laws: []law{lawParse}, issue: "#721", why: "building block: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"building block Atlas_Web_Content.Pageheader":                                     {laws: []law{lawParse}, issue: "#721", why: "building block: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"building block Atlas_Web_Content.PageheaderImage":                                {laws: []law{lawParse}, issue: "#721", why: "building block: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"building block Atlas_Web_Content.PageheaderImage_WithBack":                       {laws: []law{lawParse}, issue: "#721", why: "building block: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"building block Atlas_Web_Content.PageheaderImage_WithControls":                   {laws: []law{lawParse}, issue: "#721", why: "building block: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"building block Atlas_Web_Content.Pageheader_WithBack":                            {laws: []law{lawParse}, issue: "#721", why: "building block: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"building block Atlas_Web_Content.Pageheader_WithControls":                        {laws: []law{lawParse}, issue: "#721", why: "building block: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"building block Atlas_Web_Content.Pageheader_WithSearch":                          {laws: []law{lawParse}, issue: "#721", why: "building block: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"building block Atlas_Web_Content.Timeline":                                       {laws: []law{lawParse}, issue: "#721", why: "building block: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"building block Atlas_Web_Content.Timeline_WithImage":                             {laws: []law{lawParse}, issue: "#721", why: "building block: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"building block Atlas_Web_Content.Wizard_Arrow":                                   {laws: []law{lawParse}, issue: "#721", why: "building block: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"building block Atlas_Web_Content.Wizard_Arrow_Step":                              {laws: []law{lawParse}, issue: "#721", why: "building block: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"building block Atlas_Web_Content.Wizard_Circle":                                  {laws: []law{lawParse}, issue: "#721", why: "building block: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"building block Atlas_Web_Content.Wizard_Circle_Step":                             {laws: []law{lawParse}, issue: "#721", why: "building block: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"building block FeedbackModule.FeedbackWidget":                                    {laws: []law{lawParse}, issue: "#721", why: "building block: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"entity Mappings.Customer":                                                        {laws: []law{lawGetPut}, issue: "#721", why: "entity: breaks getput on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"entity Mappings.Order":                                                           {laws: []law{lawGetPut}, issue: "#721", why: "entity: breaks getput on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"entity Mappings.OrderLine":                                                       {laws: []law{lawGetPut}, issue: "#721", why: "entity: breaks getput on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"entity Mappings.Product":                                                         {laws: []law{lawGetPut}, issue: "#721", why: "entity: breaks getput on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"entity WorkflowCommons.ConflictedWorkflowDefinitionView":                         {laws: []law{lawGetPut, lawPutGet}, issue: "#721", why: "entity: breaks getput and putget on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"entity WorkflowCommons.ConflictedWorkflowView":                                   {laws: []law{lawExec}, issue: "#721", why: "entity: breaks exec on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"entity WorkflowCommons.MyInitiatedWorkflowView":                                  {laws: []law{lawExec}, issue: "#721", why: "entity: breaks exec on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"entity WorkflowCommons.UserTaskView":                                             {laws: []law{lawExec}, issue: "#721", why: "entity: breaks exec on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"entity WorkflowCommons.WorkflowAttachment":                                       {laws: []law{lawGetPut, lawPutGet}, issue: "#721", why: "entity: breaks getput and putget on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"entity WorkflowCommons.WorkflowAuditTrailRecord":                                 {laws: []law{lawExec}, issue: "#721", why: "entity: breaks exec on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"entity WorkflowCommons.WorkflowComment":                                          {laws: []law{lawGetPut, lawPutGet}, issue: "#721", why: "entity: breaks getput and putget on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"entity WorkflowCommons.WorkflowGroupView":                                        {laws: []law{lawParse}, issue: "#721", why: "entity: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"entity WorkflowCommons.WorkflowUserTaskView":                                     {laws: []law{lawExec}, issue: "#721", why: "entity: breaks exec on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"entity WorkflowCommons.WorkflowView":                                             {laws: []law{lawExec}, issue: "#721", why: "entity: breaks exec on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"enumeration WorkflowCommons.Enum_NotificationArea_RenderAs":                      {laws: []law{lawGetPut}, issue: "#721", why: "enumeration: breaks getput on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"export mapping Clients.SoapOrderExportMapping":                                   {laws: []law{lawGetPut}, issue: "#721", why: "export mapping: breaks getput on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"export mapping Services.OrdersExportMapping":                                     {laws: []law{lawGetPut}, issue: "#721", why: "export mapping: breaks getput on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"import mapping Clients.SoapCustomerOrdersImportMapping":                          {laws: []law{lawGetPut}, issue: "#721", why: "import mapping: breaks getput on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"import mapping Clients.SoapOrdersImportMapping":                                  {laws: []law{lawGetPut}, issue: "#721", why: "import mapping: breaks getput on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"javascript action DataWidgets.Reset_All_Filters":                                 {laws: []law{lawParse}, issue: "#721", why: "javascript action: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"javascript action DataWidgets.Reset_Filter":                                      {laws: []law{lawParse}, issue: "#721", why: "javascript action: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"javascript action DataWidgets.Set_Filter":                                        {laws: []law{lawParse}, issue: "#721", why: "javascript action: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"javascript action FeedbackModule.JS_GetFeedbackStorageObject":                    {laws: []law{lawParse}, issue: "#721", why: "javascript action: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"javascript action NanoflowCommons.DraftEmail":                                    {laws: []law{lawParse}, issue: "#721", why: "javascript action: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"javascript action NanoflowCommons.FindObjectWithGUID":                            {laws: []law{lawParse}, issue: "#721", why: "javascript action: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"javascript action NanoflowCommons.Geocode":                                       {laws: []law{lawParse}, issue: "#721", why: "javascript action: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"javascript action NanoflowCommons.GetCurrentLocation":                            {laws: []law{lawParse}, issue: "#721", why: "javascript action: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"javascript action NanoflowCommons.GetCurrentLocationMinimumAccuracy":             {laws: []law{lawParse}, issue: "#721", why: "javascript action: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"javascript action NanoflowCommons.GetGuid":                                       {laws: []law{lawParse}, issue: "#721", why: "javascript action: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"javascript action NanoflowCommons.GetObjectByGuid":                               {laws: []law{lawParse}, issue: "#721", why: "javascript action: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"javascript action NanoflowCommons.GetStorageItemObject":                          {laws: []law{lawParse}, issue: "#721", why: "javascript action: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"javascript action NanoflowCommons.GetStorageItemObjectList":                      {laws: []law{lawParse}, issue: "#721", why: "javascript action: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"javascript action NanoflowCommons.RefreshEntity":                                 {laws: []law{lawParse}, issue: "#721", why: "javascript action: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"javascript action NanoflowCommons.RefreshObject":                                 {laws: []law{lawParse}, issue: "#721", why: "javascript action: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"javascript action NanoflowCommons.ReverseGeocode":                                {laws: []law{lawParse}, issue: "#721", why: "javascript action: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"javascript action NanoflowCommons.SetStorageItemObject":                          {laws: []law{lawParse}, issue: "#721", why: "javascript action: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"javascript action NanoflowCommons.SetStorageItemObjectList":                      {laws: []law{lawParse}, issue: "#721", why: "javascript action: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"javascript action NanoflowCommons.SetStorageItemString":                          {laws: []law{lawParse}, issue: "#721", why: "javascript action: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"javascript action NanoflowCommons.Share":                                         {laws: []law{lawParse}, issue: "#721", why: "javascript action: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"javascript action NanoflowCommons.ShowConfirmation":                              {laws: []law{lawParse}, issue: "#721", why: "javascript action: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"javascript action NanoflowCommons.ShowProgress":                                  {laws: []law{lawParse}, issue: "#721", why: "javascript action: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"javascript action NanoflowCommons.SignIn":                                        {laws: []law{lawParse}, issue: "#721", why: "javascript action: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"javascript action WebActions.TakePicture":                                        {laws: []law{lawParse}, issue: "#721", why: "javascript action: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"page Administration.Account_Edit":                                                {laws: []law{lawGetPut}, issue: "#721", why: "page: breaks getput on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"page Administration.Account_New":                                                 {laws: []law{lawGetPut}, issue: "#721", why: "page: breaks getput on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"page Administration.Account_Overview":                                            {laws: []law{lawGetPut}, issue: "#721", why: "page: breaks getput on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"page FeedbackModule.PopupFailure":                                                {laws: []law{lawGetPut}, issue: "#721", why: "page: breaks getput on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"page FeedbackModule.PopupSuccess":                                                {laws: []law{lawGetPut}, issue: "#721", why: "page: breaks getput on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"page FeedbackModule.ShareFeedback":                                               {laws: []law{lawGetPut}, issue: "#721", why: "page: breaks getput on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"page FeedbackModule.ShareFeedback_Logo":                                          {laws: []law{lawGetPut}, issue: "#721", why: "page: breaks getput on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"page MyFirstModule.Home_Web":                                                     {laws: []law{lawGetPut}, issue: "#721", why: "page: breaks getput on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"page Pages.EditableLIstView":                                                     {laws: []law{lawGetPut}, issue: "#721", why: "page: breaks getput on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"page WorkflowCommons.ConflictResolution":                                         {laws: []law{lawGetPut}, issue: "#721", why: "page: breaks getput on TestApp (putget struck by #721 L4), measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"page WorkflowCommons.ConflictedActivitiesHelper_JumpTo_Options":                  {laws: []law{lawGetPut}, issue: "#721", why: "page: breaks getput on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"page WorkflowCommons.ConflictedWorkflowDefinitionView":                           {laws: []law{lawGetPut}, issue: "#721", why: "page: breaks getput on TestApp (putget struck by #721 L4), measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"page WorkflowCommons.DefaultWorkflowAdmin":                                       {laws: []law{lawGetPut}, issue: "#721", why: "page: breaks getput on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"page WorkflowCommons.ManageTaskAssignments":                                      {laws: []law{lawExec}, issue: "#721", why: "page: breaks exec on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"page WorkflowCommons.MyInitiatedWorkflowView_WithdrawConfirmation":               {laws: []law{lawGetPut}, issue: "#721", why: "page: breaks getput on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"page WorkflowCommons.MyInitiatedWorkflows":                                       {laws: []law{lawGetPut}, issue: "#721", why: "page: breaks getput on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"page WorkflowCommons.TaskAssignmentHelper_UserTask_Reassign":                     {laws: []law{lawExec}, issue: "#721", why: "page: breaks exec on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"page WorkflowCommons.TaskAssignmentHelper_UserTask_Reassign_TargetUserOptions":   {laws: []law{lawGetPut}, issue: "#721", why: "page: breaks getput on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"page WorkflowCommons.TaskAssignmentHelper_UserTask_Retarget":                     {laws: []law{lawExec}, issue: "#721", why: "page: breaks exec on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"page WorkflowCommons.TaskAssignmentHelper_UserTask_Retarget_TargetUserOptions":   {laws: []law{lawGetPut}, issue: "#721", why: "page: breaks getput on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"page WorkflowCommons.TaskAssignmentHelper_UserTask_Unassign_TargetUserOptions":   {laws: []law{lawGetPut}, issue: "#721", why: "page: breaks getput on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"page WorkflowCommons.TaskDashboard":                                              {laws: []law{lawGetPut}, issue: "#721", why: "page: breaks getput on TestApp (putget struck by #721 L4), measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"page WorkflowCommons.TaskInbox":                                                  {laws: []law{lawGetPut}, issue: "#721", why: "page: breaks getput on TestApp (putget struck by #721 L4), measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"page WorkflowCommons.UserTask_Assign":                                            {laws: []law{lawGetPut}, issue: "#721", why: "page: breaks getput on TestApp (putget since this branch's widget fixes), measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"page WorkflowCommons.UserTask_Target":                                            {laws: []law{lawGetPut}, issue: "#721", why: "page: breaks getput on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"page WorkflowCommons.UserTask_TargetGroups":                                      {laws: []law{lawGetPut}, issue: "#721", why: "page: breaks getput on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"page WorkflowCommons.User_WorkflowGroup_Select":                                  {laws: []law{lawGetPut}, issue: "#721", why: "page: breaks getput on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"page WorkflowCommons.WorkflowAttachment_New":                                     {laws: []law{lawGetPut, lawPutGet}, issue: "#721", why: "page: breaks getput and putget on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"page WorkflowCommons.WorkflowAttachment_View":                                    {laws: []law{lawExec}, issue: "#721", why: "page: breaks exec on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"page WorkflowCommons.WorkflowAuditTrailRecord_Overview":                          {laws: []law{lawGetPut}, issue: "#721", why: "page: breaks getput on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"page WorkflowCommons.WorkflowCommentHelper_Edit":                                 {laws: []law{lawGetPut}, issue: "#721", why: "page: breaks getput on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"page WorkflowCommons.WorkflowComment_Edit_Admin":                                 {laws: []law{lawGetPut}, issue: "#721", why: "page: breaks getput on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"page WorkflowCommons.WorkflowDefinition_CleanUp":                                 {laws: []law{lawGetPut}, issue: "#721", why: "page: breaks getput on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"page WorkflowCommons.WorkflowDefinition_CleanUp_Preview":                         {laws: []law{lawGetPut}, issue: "#721", why: "page: breaks getput on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"page WorkflowCommons.WorkflowDefinition_Overview":                                {laws: []law{lawGetPut}, issue: "#721", why: "page: breaks getput on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"page WorkflowCommons.WorkflowDefinition_View":                                    {laws: []law{lawExec}, issue: "#721", why: "page: breaks exec on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"page WorkflowCommons.WorkflowEndedUserTask":                                      {laws: []law{lawGetPut}, issue: "#721", why: "page: breaks getput on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"page WorkflowCommons.WorkflowGroup_Edit":                                         {laws: []law{lawExec}, issue: "#721", why: "page: breaks exec on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"page WorkflowCommons.WorkflowGroup_Overview":                                     {laws: []law{lawGetPut}, issue: "#721", why: "page: breaks getput on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"page WorkflowCommons.WorkflowGroup_User_Select":                                  {laws: []law{lawGetPut}, issue: "#721", why: "page: breaks getput on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"page WorkflowCommons.WorkflowSubProcess_View":                                    {laws: []law{lawExec}, issue: "#721", why: "page: breaks exec on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"page WorkflowCommons.WorkflowUserTaskView_View":                                  {laws: []law{lawGetPut}, issue: "#721 #826", why: "executes since describe prints snippet call Params (#826); the page Appearance keeps 1 of 3 DesignProperties (#721 C)"},
	"page WorkflowCommons.Workflow_Dashboard":                                         {laws: []law{lawGetPut}, issue: "#721", why: "page: breaks getput on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"page WorkflowCommons.Workflow_JumpTo_Options":                                    {laws: []law{lawGetPut}, issue: "#721", why: "page: breaks getput on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"rest client Clients.OrdersRestClient":                                            {laws: []law{lawParse}, issue: "#721", why: "rest client: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"rest client Mappings.RestClient":                                                 {laws: []law{lawParse}, issue: "#721", why: "rest client: breaks parse on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"rule Rules.Rule1":                                                                {laws: []law{lawGetPut}, issue: "#721", why: "rule: breaks getput on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"rule Rules.Rule2":                                                                {laws: []law{lawGetPut}, issue: "#721", why: "rule: breaks getput on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"scheduled event WorkflowCommons.SE_WorkflowAuditTrailRecord_CleanUp":             {laws: []law{lawGetPut}, issue: "#721", why: "scheduled event: breaks getput on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"snippet Administration.ReadMe":                                                   {laws: []law{lawGetPut}, issue: "#721", why: "snippet: breaks getput on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"snippet Atlas_Core.FeedbackWidget":                                               {laws: []law{lawGetPut}, issue: "#721", why: "snippet: breaks getput on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"snippet WorkflowCommons.Readme":                                                  {laws: []law{lawGetPut}, issue: "#721", why: "snippet: breaks getput on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"snippet WorkflowCommons.Snip_Assignee_Search":                                    {laws: []law{lawGetPut}, issue: "#721", why: "snippet: breaks exec on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes; executes since a widget bound to a snippet parameter is described as $Param.Attr — getput not yet triaged"},
	"snippet WorkflowCommons.Snip_AuditTrailViewer_Toolbar":                           {laws: []law{lawGetPut, lawPutGet}, issue: "#721", why: "snippet: breaks getput and putget on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"snippet WorkflowCommons.Snip_MyInitiatedWorkflowView_NotificationArea":           {laws: []law{lawGetPut, lawPutGet}, issue: "#721", why: "snippet: breaks getput and putget on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"snippet WorkflowCommons.Snip_MyInitiatedWorkflowView_StateCircleOnly":            {laws: []law{lawGetPut, lawPutGet}, issue: "#721", why: "snippet: breaks getput and putget on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"snippet WorkflowCommons.Snip_TaskAssignmentHelper_Assignee_Search":               {laws: []law{lawGetPut}, issue: "#721", why: "snippet: breaks exec on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes; executes since a widget bound to a snippet parameter is described as $Param.Attr — getput not yet triaged"},
	"snippet WorkflowCommons.Snip_TaskAssignmentHelper_TargetUser_Search":             {laws: []law{lawGetPut}, issue: "#721", why: "snippet: breaks exec on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes; executes since a widget bound to a snippet parameter is described as $Param.Attr — getput not yet triaged"},
	"snippet WorkflowCommons.Snip_TaskAssignment_UserTask_Assignees":                  {laws: []law{lawGetPut, lawPutGet}, issue: "#721", why: "snippet: breaks getput and putget on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"snippet WorkflowCommons.Snip_TaskAssignment_UserTask_TargetUsers":                {laws: []law{lawGetPut, lawPutGet}, issue: "#721", why: "snippet: breaks getput and putget on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"snippet WorkflowCommons.Snip_TaskCount_RefreshBTN":                               {laws: []law{lawGetPut}, issue: "#721", why: "snippet: breaks getput on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"snippet WorkflowCommons.Snip_TaskDashboard_Numbers":                              {laws: []law{lawGetPut}, issue: "#721", why: "snippet: breaks getput on TestApp (putget struck by #721 L4), measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"snippet WorkflowCommons.Snip_TimelineViewer_Timeline_Full":                       {laws: []law{lawExec}, issue: "#721", why: "snippet: breaks exec on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"snippet WorkflowCommons.Snip_TimelineViewer_Timeline_Tasks":                      {laws: []law{lawExec}, issue: "#721", why: "snippet: breaks exec on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"snippet WorkflowCommons.Snip_UserTask_Detail":                                    {laws: []law{lawExec}, issue: "#721", why: "snippet: breaks exec on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"snippet WorkflowCommons.Snip_UserTask_DueDate_Warning":                           {laws: []law{lawGetPut}, issue: "#721", why: "snippet: breaks getput on TestApp (#743); putget passes since a template parameter written as an expression is stored as one (#823 option C)"},
	"snippet WorkflowCommons.Snip_UserTask_Header":                                    {laws: []law{lawGetPut}, issue: "#721", why: "snippet: breaks getput on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"snippet WorkflowCommons.Snip_UserTask_NameColumn":                                {laws: []law{lawGetPut, lawPutGet}, issue: "#721 #826", why: "executes since describe prints snippet call Params (#826); an association-path template parameter read from a snippet parameter loses its AttributeRef and SourceVariable (#721)"},
	"snippet WorkflowCommons.Snip_UserTask_NotificationArea":                          {laws: []law{lawGetPut, lawPutGet}, issue: "#721", why: "snippet: breaks getput and putget on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"snippet WorkflowCommons.Snip_UserTask_UnassignedMessage":                         {laws: []law{lawGetPut}, issue: "#721", why: "snippet: breaks getput on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"snippet WorkflowCommons.Snip_WorkflowActivityRecord_ActivityIcon":                {laws: []law{lawExec}, issue: "#721", why: "snippet: breaks exec on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"snippet WorkflowCommons.Snip_WorkflowActivityRecord_Details":                     {laws: []law{lawGetPut}, issue: "#721", why: "snippet: breaks exec on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes; executes since a widget bound to a snippet parameter is described as $Param.Attr — getput not yet triaged"},
	"snippet WorkflowCommons.Snip_WorkflowActivityRecord_Header":                      {laws: []law{lawGetPut, lawPutGet}, issue: "#721 #826", why: "executes since describe prints snippet call Params (#826); association-path template parameters, a module-role visibility and an expression parameter drift (#721)"},
	"snippet WorkflowCommons.Snip_WorkflowActivityRecord_TaskDueDate_Warning":         {laws: []law{lawGetPut}, issue: "#721", why: "snippet: breaks getput on TestApp (#743); putget passes since a template parameter written as an expression is stored as one (#823 option C)"},
	"snippet WorkflowCommons.Snip_WorkflowActivity_Details_ActivityType":              {laws: []law{lawExec}, issue: "#721", why: "snippet: breaks exec on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"snippet WorkflowCommons.Snip_WorkflowAuditTrailRecord_Overview":                  {laws: []law{lawExec}, issue: "#721", why: "snippet: breaks exec on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"snippet WorkflowCommons.Snip_WorkflowDashboard_TaskNumbers":                      {laws: []law{lawGetPut}, issue: "#721", why: "snippet: breaks getput and putget on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"snippet WorkflowCommons.Snip_WorkflowDashboard_WorkflowNumbers":                  {laws: []law{lawGetPut}, issue: "#721", why: "snippet: breaks getput on TestApp (#743); putget passes since a template parameter written as an expression is stored as one (#823 option C)"},
	"snippet WorkflowCommons.Snip_WorkflowDefinition_AuditTrail":                      {laws: []law{lawExec}, issue: "#721", why: "snippet: breaks exec on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"snippet WorkflowCommons.Snip_WorkflowDefinition_Header":                          {laws: []law{lawGetPut}, issue: "#721", why: "snippet: breaks exec on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes; executes since a widget bound to a snippet parameter is described as $Param.Attr — getput not yet triaged"},
	"snippet WorkflowCommons.Snip_WorkflowEndedUserTask_Header":                       {laws: []law{lawGetPut}, issue: "#721", why: "snippet: breaks getput on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"snippet WorkflowCommons.Snip_WorkflowSubProcess_Details":                         {laws: []law{lawExec}, issue: "#721", why: "snippet: breaks exec on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"snippet WorkflowCommons.Snip_WorkflowSubProcess_IncompatibleWarning":             {laws: []law{lawExec}, issue: "#721", why: "snippet: breaks exec on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"snippet WorkflowCommons.Snip_WorkflowSubProcess_State":                           {laws: []law{lawExec}, issue: "#721", why: "snippet: breaks exec on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"snippet WorkflowCommons.Snip_WorkflowUserTaskView_Details":                       {laws: []law{lawExec}, issue: "#721", why: "snippet: breaks exec on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"snippet WorkflowCommons.Snip_WorkflowUserTaskView_DueDate_Warning":               {laws: []law{lawGetPut}, issue: "#721", why: "snippet: breaks getput on TestApp (#743); putget passes since a template parameter written as an expression is stored as one (#823 option C)"},
	"snippet WorkflowCommons.Snip_WorkflowUserTaskView_NameColumn":                    {laws: []law{lawGetPut, lawPutGet}, issue: "#721 #826", why: "executes since describe prints snippet call Params (#826); an association-path template parameter read from a snippet parameter loses its AttributeRef and SourceVariable (#721)"},
	"snippet WorkflowCommons.Snip_Workflow_ActivityTimelineOnly_Full":                 {laws: []law{lawGetPut}, issue: "#721", why: "snippet: breaks getput on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"snippet WorkflowCommons.Snip_Workflow_ActivityTimelineOnly_Tasks":                {laws: []law{lawGetPut}, issue: "#721", why: "snippet: breaks getput on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"snippet WorkflowCommons.Snip_Workflow_AuditTrail":                                {laws: []law{lawExec}, issue: "#721", why: "snippet: breaks exec on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"snippet WorkflowCommons.Snip_Workflow_CommentsAndAttachments":                    {laws: []law{lawExec}, issue: "#721", why: "snippet: breaks exec on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"snippet WorkflowCommons.Snip_Workflow_CommentsAndAttachments_Admin":              {laws: []law{lawExec}, issue: "#721", why: "snippet: breaks exec on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"snippet WorkflowCommons.Snip_Workflow_Detail":                                    {laws: []law{lawGetPut}, issue: "#721", why: "snippet: breaks exec on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes; executes since a widget bound to a snippet parameter is described as $Param.Attr — getput not yet triaged"},
	"snippet WorkflowCommons.Snip_Workflow_DueDate_Warning":                           {laws: []law{lawGetPut}, issue: "#721", why: "snippet: breaks getput on TestApp (#743); putget passes since a template parameter written as an expression is stored as one (#823 option C)"},
	"snippet WorkflowCommons.Snip_Workflow_Header":                                    {laws: []law{lawGetPut, lawPutGet}, issue: "#721 #826", why: "executes since describe prints snippet call Params (#826); an association-path caption parameter read from a snippet parameter loses its AttributeRef and SourceVariable (#721)"},
	"snippet WorkflowCommons.Snip_Workflow_NotificationArea":                          {laws: []law{lawGetPut, lawPutGet}, issue: "#721", why: "snippet: breaks getput and putget on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"snippet WorkflowCommons.Snip_Workflow_StateCircleOnly":                           {laws: []law{lawGetPut, lawPutGet}, issue: "#721", why: "snippet: breaks getput and putget on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"snippet WorkflowCommons.Snip_Workflow_SubProcessDetails":                         {laws: []law{lawExec}, issue: "#721", why: "snippet: breaks exec on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
	"snippet WorkflowCommons.Snip_Workflow_TaskDetails":                               {laws: []law{lawGetPut}, issue: "#721", why: "snippet: breaks getput on TestApp, measured when it joined the harness (#743); not yet triaged into #721's classes"},
}

// createOrModifyProbeKnownFailures is the allowlist of
// TestTestAppCreateOrModifyProbe. It may only shrink; a kind switches its
// describe verb once none of its documents is listed here.
var createOrModifyProbeKnownFailures = map[string]knownFailure{}
