// SPDX-License-Identifier: Apache-2.0

package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// init_hook.go emits a Claude Code SessionStart hook into .claude/settings.json so
// a fresh (or reaped-and-resumed) session self-bootstraps: it caches MxBuild +
// runtime and provisions the local database, leaving the session ready to
// `mxcli run --local`. Background processes (Postgres, the JVM) are reaped on
// idle, so this idempotent bring-up must run on every session start.
//
// The hook is setup-only (non-blocking): it must return, so it prepares
// prerequisites and exits rather than booting the long-lived warm loop.

// bootstrapScriptName is the committed script the SessionStart hook runs,
// relative to the project root.
const bootstrapScriptName = ".claude/bootstrap-mxcli.sh"

// bootstrapScriptTemplate is written to bootstrapScriptName. %s is the .mpr file
// name. It is POSIX sh (no bashisms) and safe to re-run: every step is a no-op
// once satisfied.
//
// It is COMMITTED on purpose — the opposite of the mxcli binary, which
// .gitignore excludes for its size. After an idle reap the container is
// reclaimed and the repo re-cloned, and this file is then the only thing in the
// tree that can bring the binary back.
const bootstrapScriptTemplate = `#!/bin/sh
# Generated by 'mxcli init'. COMMIT THIS FILE.
#
# Run by the Claude Code SessionStart hook to make a fresh (or reaped and
# re-cloned) session ready to work: fetch mxcli if the binary is missing, then
# cache MxBuild + the runtime and provision the local database.
#
# The mxcli binary is git-ignored (~85 MB), so after an idle reap it is NOT in
# the fresh clone — which is exactly why this script fetches it rather than
# skipping when it is absent.
#
# Pin a specific mxcli with MXCLI_TAG=vX.Y.Z (default: nightly).
set -e

MPR='%s'
TAG="${MXCLI_TAG:-nightly}"

if [ ! -x ./mxcli ]; then
  # Prefer a copy that is already on this machine. Some environments ship mxcli
  # pre-installed on PATH, and the bootstrap instructions have you delete the
  # hardlink 'mxcli new' left in the project — after which this guard could
  # never be satisfied by the PATH binary and re-downloaded ~85 MB on EVERY
  # fresh session, forever. (ako/ChipCoV1)
  #
  # Hardlink first because that is what 'mxcli new' does and it costs nothing;
  # fall back to a symlink across filesystems, then to a copy. Any of the three
  # leaves ./mxcli working, which is what the rest of this script and the
  # project's own CLAUDE.md assume.
  onpath=$(command -v mxcli 2>/dev/null || true)
  if [ -n "$onpath" ] && [ -x "$onpath" ]; then
    echo "mxcli found on PATH (${onpath}) — linking it in rather than downloading."
    ln -f "$onpath" ./mxcli 2>/dev/null ||
      ln -sf "$onpath" ./mxcli 2>/dev/null ||
      cp "$onpath" ./mxcli
    chmod +x ./mxcli 2>/dev/null || true
  fi
fi

if [ ! -x ./mxcli ]; then
  os=$(uname -s | tr 'A-Z' 'a-z')
  case "$(uname -m)" in
    x86_64|amd64) arch=amd64 ;;
    arm64|aarch64) arch=arm64 ;;
    *) arch=$(uname -m) ;;
  esac
  url="https://github.com/mendixlabs/mxcli/releases/download/${TAG}/mxcli-${os}-${arch}"
  echo "mxcli not found — downloading ${TAG} for ${os}/${arch}..."
  if ! curl -fsSL -o ./mxcli "$url"; then
    echo "Could not download mxcli from ${url}." >&2
    echo "Fetch it manually, or set MXCLI_TAG to a released version." >&2
    exit 1
  fi
  chmod +x ./mxcli
fi

# Keep .ai-context/skills/ in step with this binary. The skills are embedded in
# mxcli and written once by 'mxcli init', so upgrading the binary used to leave
# yesterday's guidance in place with no warning — and an agent reads stale
# guidance with the same confidence as current guidance. Quiet when already
# current; never fatal, since a skills refresh must not block the session.
./mxcli init --sync-skills . || true

exec ./mxcli run --local --setup --ensure-db -p "$MPR"
`

// sessionStartHookMarkers identify OUR hook command — so re-running init updates
// it instead of duplicating it, and a user's own SessionStart hooks are never
// touched. The first is the current form; the rest are older spellings kept so
// existing projects migrate rather than accumulate a second hook.
var sessionStartHookMarkers = []string{
	bootstrapScriptName,   // current: the committed bootstrap script
	"run --local --setup", // pre-bootstrap-script: the command inlined in the hook
}

// isMxcliSessionStartHook reports whether a hook command is one mxcli wrote.
func isMxcliSessionStartHook(command string) bool {
	for _, m := range sessionStartHookMarkers {
		if strings.Contains(command, m) {
			return true
		}
	}
	return false
}

// sessionStartHookCommand is the shell command the hook runs. It delegates to a
// committed script rather than inlining the work, for two reasons:
//
//  1. The inlined form was guarded on `test -x ./mxcli`, and the binary it
//     guards on is git-ignored (~85 MB, deliberately). In an ephemeral container
//     the repo is re-cloned after an idle reap, `./mxcli` is not in the clone,
//     the guard fails and the hook silently no-ops through `|| true` — leaving
//     exactly the unprepared session the hook exists to prevent, with no error
//     saying so. The script can fetch the binary back; a hook line cannot
//     reasonably do OS/arch detection. (mxcli-todo findings #2)
//  2. The command string stays constant, so re-running `mxcli init` recognises
//     its own hook even when the project is renamed.
func sessionStartHookCommand() string {
	return fmt.Sprintf("sh %s || true", bootstrapScriptName)
}

// ensureSessionStartHook adds (idempotently) the mxcli bring-up to
// .claude/settings.json, preserving any existing settings/hooks. It returns
// whether a change was written. If settings.json exists but is not valid JSON it
// is left untouched (changed=false) with an error, so we never destroy content.
func ensureSessionStartHook(claudeDir, mprFile string) (changed bool, err error) {
	path := filepath.Join(claudeDir, "settings.json")

	// The script is rewritten every time so a renamed .mpr (or an improvement to
	// the script itself) is picked up; it holds no user content.
	scriptChanged, err := writeBootstrapScript(claudeDir, mprFile)
	if err != nil {
		return false, err
	}

	settings := map[string]any{}
	if data, readErr := os.ReadFile(path); readErr == nil {
		if json.Unmarshal(data, &settings) != nil {
			return scriptChanged, fmt.Errorf("%s exists but is not valid JSON; leaving it untouched — add a SessionStart hook manually", path)
		}
	}

	if updated := addSessionStartHook(settings, sessionStartHookCommand()); !updated {
		return scriptChanged, nil // hook already current
	}

	out, err := json.MarshalIndent(settings, "", "  ")
	if err != nil {
		return false, err
	}
	out = append(out, '\n')
	if err := os.WriteFile(path, out, 0o644); err != nil {
		return false, err
	}
	return true, nil
}

// writeBootstrapScript writes (or refreshes) the committed bootstrap script the
// SessionStart hook runs. Reports whether the content changed.
func writeBootstrapScript(claudeDir, mprFile string) (changed bool, err error) {
	// claudeDir is <project>/.claude and bootstrapScriptName is project-relative,
	// so take the base name to land beside settings.json.
	path := filepath.Join(claudeDir, filepath.Base(bootstrapScriptName))
	want := []byte(fmt.Sprintf(bootstrapScriptTemplate, mprFile))
	if existing, readErr := os.ReadFile(path); readErr == nil && bytes.Equal(existing, want) {
		return false, nil
	}
	if err := os.MkdirAll(claudeDir, 0o755); err != nil {
		return false, err
	}
	if err := os.WriteFile(path, want, 0o755); err != nil {
		return false, fmt.Errorf("writing %s: %w", path, err)
	}
	return true, nil
}

// addSessionStartHook inserts a SessionStart command hook into a parsed settings
// map, preserving existing keys and hooks. An entry matching any known marker is
// UPDATED in place rather than duplicated, so a project written by an older
// mxcli (which inlined the whole command) migrates to the current one instead of
// ending up with two hooks that both run. Returns whether anything changed.
// Operates on the generic JSON shape so it never drops unknown settings.
func addSessionStartHook(settings map[string]any, command string) bool {
	hooks, _ := settings["hooks"].(map[string]any)
	if hooks == nil {
		hooks = map[string]any{}
	}
	sessionStart, _ := hooks["SessionStart"].([]any)

	for _, entry := range sessionStart {
		em, ok := entry.(map[string]any)
		if !ok {
			continue
		}
		inner, _ := em["hooks"].([]any)
		for _, h := range inner {
			hm, ok := h.(map[string]any)
			if !ok {
				continue
			}
			c, _ := hm["command"].(string)
			if !isMxcliSessionStartHook(c) {
				continue
			}
			if c == command {
				return false // already current
			}
			hm["command"] = command
			settings["hooks"] = hooks
			return true
		}
	}

	sessionStart = append(sessionStart, map[string]any{
		"hooks": []any{
			map[string]any{"type": "command", "command": command},
		},
	})
	hooks["SessionStart"] = sessionStart
	settings["hooks"] = hooks
	return true
}
