// SPDX-License-Identifier: Apache-2.0

package theme

import (
	"fmt"
	"strings"
)

// SwitcherMDL returns the MDL that installs a runtime theme switcher into
// module. The browser-storage key is substituted rather than written into the
// template literally, so SwitcherStorageKey cannot drift from what the
// generated JavaScript actually reads.
//
// This is the one part of theming that cannot be files alone. A theme's
// light/dark blocks key off a class on the root element, and nothing in Mendix
// puts it there: Atlas ships the `:root.theme-dark` slot but no switcher, and
// there is no theme-level hook to run script before first paint —
// deployment/web/index.html is generated by mxbuild, and theme/web/settings.json
// only accepts cssFiles. So an explicit user choice has to come from the model:
// JavaScript actions the client can run, wrapped in nanoflows a button can call.
//
// The CSS still does the heavy lifting. `--variant auto` already renders the
// right palette before first paint by following the OS, so the switcher only
// has to handle the case where a user's stored choice differs from their OS
// preference — which is also the only case that can flash.
// skins is the switchable set installed in the project, default first. With
// fewer than two, the skin actions are left out rather than generated to cycle
// a set of one.
func SwitcherMDL(module string, skins []string) string {
	r := strings.NewReplacer(
		"{{MODULE}}", module,
		"{{STORAGE_KEY}}", SwitcherStorageKey,
		"{{SKIN_STORAGE_KEY}}", SkinStorageKey,
		"{{SKIN_PREFIX}}", SkinClassPrefix,
		"{{SKINS}}", jsStringArray(skins),
		"{{DEFAULT_SKIN}}", firstOr(skins, ""),
	)
	out := r.Replace(switcherTemplate)
	if len(skins) > 1 {
		out += r.Replace(skinSwitcherTemplate)
	}
	return out
}

// SwitcherStorageKey is where an explicit light/dark choice is remembered.
const SwitcherStorageKey = "mxcli-theme"

// SkinStorageKey is where an explicit theme choice is remembered. Separate
// from the variant: a user who picks Ledger and then flips to dark expects
// Ledger's dark palette, not to have lost their theme.
const SkinStorageKey = "mxcli-skin"

// jsStringArray renders a skin list as a JavaScript array literal. The names
// are validated theme names, so quoting is enough.
func jsStringArray(names []string) string {
	quoted := make([]string, len(names))
	for i, n := range names {
		quoted[i] = `"` + n + `"`
	}
	return "[" + strings.Join(quoted, ", ") + "]"
}

func firstOr(s []string, fallback string) string {
	if len(s) == 0 {
		return fallback
	}
	return s[0]
}

const switcherTemplate = `-- Runtime theme switcher, installed by ` + "`mxcli theme switcher install`" + `.
--
-- The theme's SCSS already ships both palettes and follows the OS. These
-- actions exist for the one thing CSS cannot do: let a user override that
-- choice and have it remembered.
--
-- The class goes on <html> (":root"), so popups and modals — which Mendix
-- renders at <body>, outside any page container — follow it too.

-- Flip between light and dark, resolving "follow the OS" to whatever the OS is
-- currently saying, and remember the choice. Returns the theme now in force.
create or modify javascript action {{MODULE}}.ToggleAppTheme() returns String
exposed as 'Toggle app theme' in 'Theme'
as $$
var root = document.documentElement;
var effective;
if (root.classList.contains("theme-dark")) {
    effective = "dark";
} else if (root.classList.contains("theme-light")) {
    effective = "light";
} else {
    effective = window.matchMedia && window.matchMedia("(prefers-color-scheme: dark)").matches
        ? "dark"
        : "light";
}
var next = effective === "dark" ? "light" : "dark";
root.classList.remove("theme-light", "theme-dark");
root.classList.add("theme-" + next);
try {
    window.localStorage.setItem("{{STORAGE_KEY}}", next);
} catch (e) {
    // Private browsing and some embedded webviews reject storage; the class is
    // already applied, so the only thing lost is persistence across reloads.
}
return Promise.resolve(next);
$$;

-- Set the theme explicitly. Pass "auto" to drop the override and go back to
-- following the OS.
create or modify javascript action {{MODULE}}.SetAppTheme(
  Theme: String not null
) returns Boolean
exposed as 'Set app theme' in 'Theme'
as $$
var root = document.documentElement;
root.classList.remove("theme-light", "theme-dark");
try {
    if (Theme === "light" || Theme === "dark") {
        root.classList.add("theme-" + Theme);
        window.localStorage.setItem("{{STORAGE_KEY}}", Theme);
    } else {
        window.localStorage.removeItem("{{STORAGE_KEY}}");
    }
} catch (e) {
    if (Theme === "light" || Theme === "dark") {
        root.classList.add("theme-" + Theme);
    }
}
return Promise.resolve(true);
$$;

-- Re-apply a remembered choice. Nothing calls this automatically: Mendix pages
-- have no on-load event, and the usual substitute — a data view whose data
-- source is a nanoflow — is not something mxcli can author yet (the modelsdk
-- engine refuses a NanoflowSource data view, and the legacy engine writes one
-- with the nanoflow reference missing, which fails the build with "No nanoflow
-- configured for the data source of this data view"). Until that is closed,
-- wire it in Studio Pro if you want an explicit choice to survive a reload.
create or modify javascript action {{MODULE}}.ApplyStoredTheme() returns Boolean
exposed as 'Apply stored theme' in 'Theme'
as $$
var stored = null;
try {
    stored = window.localStorage.getItem("{{STORAGE_KEY}}");
} catch (e) {
    // No storage available: following the OS is the right fallback.
}
var root = document.documentElement;
root.classList.remove("theme-light", "theme-dark");
if (stored === "light" || stored === "dark") {
    root.classList.add("theme-" + stored);
}
return Promise.resolve(true);
$$;

-- Wire this to a button: actionbutton btnTheme (caption: 'Theme', action: nanoflow {{MODULE}}.ACT_ToggleTheme)
create or replace nanoflow {{MODULE}}.ACT_ToggleTheme()
returns String as $Theme
begin
  $Theme = call javascript action {{MODULE}}.ToggleAppTheme();
  return $Theme;
end;

-- Ready for whatever ends up calling it on load; nothing does today (see above).
create or replace nanoflow {{MODULE}}.ACT_ApplyStoredTheme()
returns Boolean as $Applied
begin
  $Applied = call javascript action {{MODULE}}.ApplyStoredTheme();
  return $Applied;
end;
`

// SwitcherNextSteps is printed after an install: the wiring mxcli does not do
// for the user, because it lands on a page or layout it did not create.
func SwitcherNextSteps(module string) string {
	return fmt.Sprintf(`Installed into %[1]s. One step left — add a toggle wherever it belongs,
typically a layout or a settings page:

    actionbutton btnTheme (caption: 'Theme', action: nanoflow %[1]s.ACT_ToggleTheme)

That is enough to switch: the click flips the palette and remembers the choice.

Reload behaviour: the app goes back to following the OS, because Mendix has no
page on-load event to re-apply the stored value from, and the usual substitute
(a data view with a nanoflow data source) is not authorable by mxcli yet on
either engine. %[1]s.ApplyStoredTheme is installed and ready for it — wire it in
Studio Pro if you need the choice to persist across reloads.`, module)
}

// skinSwitcherTemplate is appended when the project carries a switchable set.
//
// This is the CSS Zen Garden move: the DOM Mendix renders never changes, and
// neither does the model. Every theme in the set is already compiled into
// theme.compiled.css, each palette scoped to its own root class, so selecting
// one is a class swap — no rebuild, no reload, no server round trip.
const skinSwitcherTemplate = `
-- ---------------------------------------------------------------------------
-- Theme selection. The set installed here is {{SKINS}}, and "{{DEFAULT_SKIN}}"
-- is the one that renders before any class is set.
--
-- Every theme's palette is in the same stylesheet, scoped to :root.{{SKIN_PREFIX}}<name>,
-- so this only ever adds and removes a class on <html>. Light/dark is a
-- separate axis: picking a theme keeps whichever variant is in force.
-- ---------------------------------------------------------------------------

-- Select a theme by name. An unknown name clears the override and falls back
-- to the set's default rather than leaving the app in no theme at all.
create or modify javascript action {{MODULE}}.SetAppSkin(
  Skin: String
) returns String
exposed as 'Set app theme skin' in 'Theme'
as $$
var skins = {{SKINS}};
var root = document.documentElement;
skins.forEach(function (s) { root.classList.remove("{{SKIN_PREFIX}}" + s); });

var chosen = skins.indexOf(Skin) === -1 ? "{{DEFAULT_SKIN}}" : Skin;
root.classList.add("{{SKIN_PREFIX}}" + chosen);
try {
    window.localStorage.setItem("{{SKIN_STORAGE_KEY}}", chosen);
} catch (e) {
    // No storage available: the choice still applies for this page view.
}
return Promise.resolve(chosen);
$$;

-- Rotate to the next theme in the set. With no class set the app is showing
-- the default, so that is where the rotation starts.
create or modify javascript action {{MODULE}}.CycleAppSkin() returns String
exposed as 'Cycle app theme skin' in 'Theme'
as $$
var skins = {{SKINS}};
var root = document.documentElement;
var current = 0;
for (var i = 0; i < skins.length; i++) {
    if (root.classList.contains("{{SKIN_PREFIX}}" + skins[i])) { current = i; break; }
}
var next = skins[(current + 1) % skins.length];

skins.forEach(function (s) { root.classList.remove("{{SKIN_PREFIX}}" + s); });
root.classList.add("{{SKIN_PREFIX}}" + next);
try {
    window.localStorage.setItem("{{SKIN_STORAGE_KEY}}", next);
} catch (e) {
    // No storage available: the choice still applies for this page view.
}
return Promise.resolve(next);
$$;

-- Re-apply a remembered theme. Same caveat as ApplyStoredTheme: nothing calls
-- this automatically, because Mendix pages have no on-load event mxcli can
-- author. Wire it in Studio Pro if the choice must survive a reload.
create or modify javascript action {{MODULE}}.ApplyStoredSkin() returns Boolean
exposed as 'Apply stored theme skin' in 'Theme'
as $$
var skins = {{SKINS}};
var stored = null;
try {
    stored = window.localStorage.getItem("{{SKIN_STORAGE_KEY}}");
} catch (e) {
    // No storage available: the default is the right fallback.
}
var root = document.documentElement;
skins.forEach(function (s) { root.classList.remove("{{SKIN_PREFIX}}" + s); });
if (stored !== null && skins.indexOf(stored) !== -1) {
    root.classList.add("{{SKIN_PREFIX}}" + stored);
}
return Promise.resolve(true);
$$;

-- Wire this to a button: actionbutton btnSkin (caption: 'Theme', action: nanoflow {{MODULE}}.ACT_CycleSkin)
create or replace nanoflow {{MODULE}}.ACT_CycleSkin()
returns String as $Skin
begin
  $Skin = call javascript action {{MODULE}}.CycleAppSkin();
  return $Skin;
end;

-- Ready for whatever ends up calling it on load; nothing does today.
create or replace nanoflow {{MODULE}}.ACT_ApplyStoredSkin()
returns Boolean as $Applied
begin
  $Applied = call javascript action {{MODULE}}.ApplyStoredSkin();
  return $Applied;
end;
`
