//go:build ignore

// SPDX-License-Identifier: Apache-2.0

// gen_metamodel copies the property version data of every generated metamodel
// package (modelsdk/gen/*/version.go) into this package as plain data.
//
// The storage layer (modelsdk/canon, modelsdk/mpr) needs it to tell which
// properties a project's Mendix version declares, but cannot import the
// generated packages: they import it. Importing them elsewhere for their data
// would also run their init, which registers codec factories for every
// metamodel type — a global side effect a version lookup must not have. So the
// data is copied, and modelsdk/gen's TestVersionDataCopyMatchesGenerated fails
// when the copy drifts.
//
// Run: go generate ./modelsdk/version
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func main() {
	files, err := filepath.Glob("../gen/*/version.go")
	if err != nil || len(files) == 0 {
		fail("no generated version files found (%v)", err)
	}
	sort.Strings(files)
	var b bytes.Buffer
	b.WriteString("// Code generated by gen_metamodel.go; DO NOT EDIT.\n// Run: go generate ./modelsdk/version\n\npackage version\n\n")
	b.WriteString("// metamodelVersions is modelsdk/gen/*/version.go's VersionInfos, one map per\n// generated package, as plain data (see gen_metamodel.go for why it is a copy).\n")
	b.WriteString("var metamodelVersions = []map[string]TypeVersionInfo{\n")
	const head = "var VersionInfos = map[string]version.TypeVersionInfo{"
	for _, f := range files {
		src, err := os.ReadFile(f)
		if err != nil {
			fail("%v", err)
		}
		s := string(src)
		i := strings.Index(s, head)
		if i < 0 {
			fail("%s: no %q", f, head)
		}
		body := strings.TrimSpace(s[i+len(head)-1:]) // from the opening brace
		body = strings.ReplaceAll(body, "version.PropertyVersionInfo", "PropertyVersionInfo")
		body = strings.ReplaceAll(body, "version.TypeVersionInfo", "TypeVersionInfo")
		fmt.Fprintf(&b, "\t// %s\n\t%s,\n", filepath.Base(filepath.Dir(f)), body)
	}
	b.WriteString("}\n")
	out, err := format.Source(b.Bytes())
	if err != nil {
		fail("format: %v", err)
	}
	if err := os.WriteFile("metamodel_versions_gen.go", out, 0o644); err != nil {
		fail("%v", err)
	}
}

func fail(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "gen_metamodel: "+format+"\n", args...)
	os.Exit(1)
}
