#!/usr/bin/env python3
"""Generate docs/11-proposals/README.md from proposal frontmatter.

The header (conventions + status legend) is hand-written and preserved
verbatim; everything below the AUTOGEN marker is regenerated. Run after any
status change. Idempotent.
"""
import os
import re

P = "docs/11-proposals"
ARCHIVE = os.path.join(P, "archive")
OUT = os.path.join(P, "README.md")

HEADER = """# Proposals Index

Status of all mxcli feature proposals. See [archive/](archive/) for terminal-status proposals (done, superseded, abandoned).

## Conventions

Proposal conventions, frontmatter format, and lint rules are defined in
[`.claude/skills/lint-proposals.md`](../../.claude/skills/lint-proposals.md).
Audit and apply via `/mxcli-dev:proposal-lint`.

## Status Legend

The canonical status vocabulary (lowercase in frontmatter; capitalised
for display in this README):

| Status | Meaning | Folder |
|--------|---------|--------|
| Draft | Early design, not finalised | active |
| Proposed | Design complete, not yet started | active |
| Partial | Some phases/features implemented | active |
| Done | Fully implemented | `archive/` |
| Superseded | Replaced by a newer proposal | `archive/` |
| Abandoned | Explicitly not pursuing | `archive/` |
| Reference | Durable reference doc, not a proposal | move out of `11-proposals/` |

<!-- AUTOGEN BELOW — regenerated by scripts/gen_proposals_readme.py; do not hand-edit -->
"""


def read_fm(path):
    title = status = ""
    txt = open(path).read()
    m = re.match(r"---\n(.*?)\n---\n(.*)", txt, re.S)
    if not m:
        return None
    fm, body = m.group(1), m.group(2)
    for line in fm.splitlines():
        if line.startswith("title:"):
            title = line[6:].strip()
        elif line.startswith("status:"):
            status = line[7:].strip()
    summary = extract_summary(body)
    return title, status, summary


def extract_summary(body):
    for line in body.splitlines():
        s = line.strip()
        if not s:
            continue
        if s.startswith("#") or s.startswith(">"):
            continue
        if s.startswith("**Status") or s.startswith("**Date") or s.startswith("**Author") or s.startswith("**Supersed"):
            continue
        if s.startswith("---") or s.startswith("|") or s.startswith("```"):
            continue
        s = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", s)  # links -> text only
        s = re.sub(r"\*\*|`|\*", "", s)
        # first sentence, capped
        s = re.split(r"(?<=[.!?])\s", s)[0]
        return s[:140]
    return ""


def collect(folder):
    items = []
    for name in sorted(os.listdir(folder)):
        if not name.endswith(".md") or name == "README.md":
            continue
        path = os.path.join(folder, name)
        if not os.path.isfile(path):
            continue
        fm = read_fm(path)
        if fm:
            items.append((name, *fm))
    return items


def table(items, link_prefix=""):
    rows = ["| Proposal | Status | Summary |", "|----------|--------|---------|"]
    for name, title, status, summary in items:
        disp = title or name[:-3]
        disp = disp.replace("|", "\\|")
        summary = summary.replace("|", "\\|")
        rows.append(f"| [{disp}]({link_prefix}{name}) | {status.capitalize()} | {summary} |")
    return "\n".join(rows)


def main():
    active = collect(P)
    archived = collect(ARCHIVE)
    by_status = {"partial": [], "proposed": [], "draft": []}
    for it in active:
        by_status.setdefault(it[2], []).append(it)

    parts = [HEADER]
    parts.append(f"\n## Active Proposals ({len(active)})\n")
    for st, label in (("partial", "In Progress (partial)"),
                      ("proposed", "Proposed"),
                      ("draft", "Draft")):
        group = sorted(by_status.get(st, []), key=lambda x: x[1].lower())
        if group:
            parts.append(f"\n### {label} ({len(group)})\n")
            parts.append(table(group))
    parts.append(f"\n\n## Archived ({len(archived)})\n")
    parts.append("\nTerminal-status proposals. See [archive/](archive/).\n")
    parts.append(table(sorted(archived, key=lambda x: (x[2], x[1].lower())),
                       link_prefix="archive/"))
    parts.append("")
    open(OUT, "w").write("\n".join(parts) + "\n")
    print(f"Wrote {OUT}: {len(active)} active, {len(archived)} archived")


if __name__ == "__main__":
    main()
