#!/usr/bin/env python3
"""Insert or refresh the line-numbered section index at the top of each SKILL.md.

Why this exists. On the BENCH-001 baseline (2026-10-10) reading the skills was
~68% of the session's whole re-read cost against ~31% of its calls: one
`cat write-microflows/SKILL.md` was 7.1k tokens re-read 43 times, more than
every mxcli invocation in the costliest ten put together. The agent tried to
read part of a skill (`sed -n 314,420p`) and tried to find the sections first
(`grep -n '^## '`), so the intent was there — what was missing was a map it
could read for ~200 tokens instead of paying for the file.

The index is GENERATED, never hand-written: a hand-kept table of contents is the
drift failure this repo has already paid for twice (the gate list in three
places, the skill table at 12 of 68). `make check-skill-index` fails when a file
has moved on without it.

The block's own lines shift every range below it, so the ranges are computed to a
FIXED POINT: write, recount, rewrite, until the numbers stop moving. Without that
every range is wrong by the height of the block, which is exactly the kind of
nearly-right number that is worse than none.
"""
import glob
import os
import re
import sys

BEGIN = "<!-- skill-index: generated by scripts/skill-index.py; make check-skill-index -->"
END = "<!-- /skill-index -->"
# A section too short to be worth a jump is still listed: the point of the index
# is that the reader can choose, and a missing row reads as "not covered".
HEADING = re.compile(r"^## (.+)$")


def split_front_matter(text):
    """Return (frontmatter_including_delimiters, rest)."""
    if not text.startswith("---\n"):
        return "", text
    end = text.find("\n---\n", 4)
    if end == -1:
        return "", text
    return text[: end + 5], text[end + 5 :]


def strip_index(body):
    """Remove an existing generated block, so this is idempotent."""
    start = body.find(BEGIN)
    if start == -1:
        return body
    stop = body.find(END, start)
    if stop == -1:
        return body
    stop += len(END)
    # Also swallow the blank line that followed it.
    while stop < len(body) and body[stop] == "\n":
        stop += 1
    return body[:start] + body[stop:]


def sections(lines, offset):
    """Heading rows as (title, first_line, last_line), 1-based with offset.

    The last section ends at the last line that HAS content: a file ending in a
    newline makes split("\n") yield a trailing empty string, and pointing the
    final range one line past the end is the kind of nearly-right number this
    whole index is supposed not to be (sed tolerates it; a reader checking the
    table against the file does not)."""
    found = [(i, m.group(1).strip()) for i, l in enumerate(lines) if (m := HEADING.match(l))]
    last = len(lines) - 1
    while last > 0 and not lines[last].strip():
        last -= 1
    out = []
    for n, (i, title) in enumerate(found):
        end = found[n + 1][0] - 1 if n + 1 < len(found) else last
        out.append((title, i + 1 + offset, end + 1 + offset))
    return out


def render(rows, name):
    w = max((len(t) for t, _, _ in rows), default=0)
    body = [
        BEGIN,
        "## Find it fast",
        "",
        "`sed -n '<from>,<to>p' SKILL.md` one section rather than reading the file;",
        "`./mxcli syntax <topic>` answers *how do I write this* for a fraction of either.",
        "",
        "| lines | section |",
        "|---|---|",
    ]
    for title, a, b in rows:
        body.append("| %d-%d | %s |" % (a, b, title))
    body += ["", END, ""]
    return "\n".join(body)


def process(path, write):
    original = open(path).read()
    front, body = split_front_matter(original)
    body = strip_index(body)
    base = body.lstrip("\n")
    lead = len(front.split("\n")) - 1 if front else 0

    block = ""
    for _ in range(10):  # fixed point: the block's height shifts every range
        offset = lead + (len(block.split("\n")) - 1 if block else 0)
        rows = sections(base.split("\n"), offset)
        if not rows:
            return False, "no ## headings"
        nxt = render(rows, os.path.basename(os.path.dirname(path)))
        if nxt == block:
            break
        block = nxt
    else:
        return False, "ranges did not converge"

    out = front + block + base
    if out == original:
        return False, "unchanged"
    if write:
        open(path, "w").write(out)
    return True, "updated"


def main():
    write = "--check" not in sys.argv
    roots = ["skills/mendix", "skills"]
    paths = sorted(set(
        p for r in roots for p in glob.glob(".claude/%s/*/SKILL.md" % r)
    ))
    changed, problems = [], []
    for p in paths:
        did, why = process(p, write)
        if did:
            changed.append(p)
        elif why not in ("unchanged",):
            problems.append((p, why))
    for p, why in problems:
        print("SKIP %s: %s" % (p, why))
    if not write and changed:
        print("skill index is stale in %d file(s); run 'make skill-index':" % len(changed))
        for p in changed:
            print("  " + p)
        sys.exit(1)
    print("skill index: %d file(s) %s, %d already current"
          % (len(changed), "updated" if write else "stale", len(paths) - len(changed) - len(problems)))


main()
